### ISSUE TITLE
HW01 Ex3 Interpretation

### ISSUE THREAD

**Issue by skywang0407** [sta-363-s20/community#10]
Hi Professor McGowan,
When asked to interpret the beta coefficients for UrbanYes and USYes, since they are qualitative variables, can I interpret them as "UrbanYes compared to UrbanNo decrease the expected value of Sales by 0.022"?

![Q2](https://user-images.githubusercontent.com/59891782/73127060-d8958080-3f88-11ea-8b49-99f442b31a09.png)

Thanks!

**Comment by LucyMcGowan** [comment]
That is almost correct (missing an important part since this is **multiple** regression)

**Comment by skywang0407** [comment]
Got it, thanks!
