### ISSUE TITLE
RStudio Cloud Not Loading 

### ISSUE THREAD

**Issue by erincperry** [sta-363-s20/community#15]
RStudio Cloud is not loading for me at all now. Is anyone else having this issue?

**Comment by LucyMcGowan** [comment]
I believe this was related to the same issues seen in (#12) - RStudio Cloud is loading for me, but let me know if you are still seeing this issue.

**Comment by skyzhr621** [comment]
> I believe this was related to the same issues seen in (#12) - RStudio Cloud is loading for me, but let me know if you are still seeing this issue.
RStudio Cloud is not loading for me now... same
