### ISSUE TITLE
RStudio Cloud Question: No check boxes for committing

### ISSUE THREAD

**Issue by peytontarry** [sta-363-s20/community#16]
Hi everyone!

I have just completed one of the exercises on the homework (and knitted), but when I look in the Git window, there is nothing to check or commit. I have already knit, commit, and pushed some of my work to Git, so I'm not sure why it stopped working. Has anyone else experienced this, or does anyone know how to fix that?

Thanks!
Peyton

**Comment by LucyMcGowan** [comment]
I am guessing this is related to (#12) 
According to RStudio, the error rates have stabilized, https://status.rstudio.com, so it should be working soon.
