### ISSUE TITLE
Maximum Likelihood in logistic regression

### ISSUE THREAD

**Issue by Cindyyyhey** [sta-363-s20/community#17]
Hi Professor McGowan,

"In logistic regression, we use maximum likelihood to estimate the parameters. This likelihood give the probability of the observed ones and zeros in the data"

I'm not quite sure what does the likelihood means here? I think the probability of observing 1 and 0 as response variables in the data is fixed.

**Comment by LucyMcGowan** [comment]
It's true the observed data is fixed - what maximum likelihood is doing is trying to fit a particular _distribution_ to the data and this distribution has parameters (in this case some of the parameters are the beta coefficients in the model) - the idea is that the beta coefficients are chosen such that the probability of observing the data that was observed is maximized.

**Comment by Cindyyyhey** [comment]
thanks!! got it
