### ISSUE TITLE
no such file or directory 

### ISSUE THREAD

**Issue by huqinyi0417** [sta-363-s20/community#2]
When I try to knit the RMarkdown, it shows "no such file or directory". What's wrong with it?

**Comment by huqinyi0417** [comment]
@LucyMcGowan Sincerely ask for help......Should I ignore it and just push changes?

**Comment by huqinyi0417** [comment]
Now when I try to reopen this project, the browser runs for 10+ minutes and still could not open it......

**Comment by LucyMcGowan** [comment]
I just opened your RStudio project and it seems to be okay. I was able to knit your document as well. Are you still seeing these problems?

**Comment by huqinyi0417** [comment]
> I just opened your RStudio project and it seems to be okay. I was able to knit your document as well. Are you still seeing these problems?

Now it opens, but everything I wrote this morning has gone.......I think I have to write those codes again.
