### ISSUE TITLE
Lab 02, Problem 8: Definition of 'Accuracy'

### ISSUE THREAD

**Issue by BrianNathanWhite** [sta-363-s20/community#20]
I just wanted to confirm what the definition of 'accuracy' is in this setting. Is it it the case that:

accuracy=(# correct positives + # correct negatives)/(total # of observations)?

**Comment by BrianNathanWhite** [comment]
For the case where k=2 that is.

**Comment by LucyMcGowan** [comment]
Yes! I believe your definition also works when k > 2 as well. Another way to think of it could be 
(Number where truth == predicted) / n

**Comment by BrianNathanWhite** [comment]
Okay, that makes sense. Thanks!
