### ISSUE TITLE
Lab 02, Trouble Knitting

### ISSUE THREAD

**Issue by rachelmccrary** [sta-363-s20/community#21]
Hi @LucyMcGowan , I am having trouble with knitting my Lab 02 document in order to commit and push after exercise 9. I have been knitting, committing, and pushing just fine for every other exercise. For some reason, this time, when I click "knit" it only will knit to around 50% and then it will stop knitting but not show an error message. I have tried several things including making sure there are no errors in the code and giving it more time to complete, but none of these have worked. Do you have any tips for how to address this issue? Thank you!

**Comment by LucyMcGowan** [comment]
Can you copy the text of the error message here? That will help me troubleshoot.

**Comment by Feifan-990807** [comment]
Hi Dr. McGowan, I also had the same issue when I knitted my document. Here is the error message I got. Thank you!
<img width="636" alt="Screen Shot 2020-02-07 at 11 05 56 PM" src="https://user-images.githubusercontent.com/59888450/74078932-84fe4a80-49fe-11ea-90da-c414afdd3ac9.png">
<img width="637" alt="Screen Shot 2020-02-07 at 11 06 06 PM" src="https://user-images.githubusercontent.com/59888450/74078933-89c2fe80-49fe-11ea-9353-3f52bbd0329b.png">
<img width="629" alt="Screen Shot 2020-02-07 at 11 06 15 PM" src="https://user-images.githubusercontent.com/59888450/74078937-8f204900-49fe-11ea-8515-9049967b5907.png">

**Comment by LucyMcGowan** [comment]
Does it not get to 100%? What you have pasted so far doesn’t look like an error to me.

**Comment by LutionHan** [comment]
Hi Dr. McGowan, I believe I have probably the same issue. My knitting stuck on ex 5 and does not give me an error. I can successfully knit when I complete ex 8. However, once I complete ex 9, my knitting will stuck on ex 5 forever. 
I could run all mu chunks without any error. 
I have tried putting 
"train$lda_predicted_class <- NULL" before my ex.9 but it still does not work.
The following is my chunks for ex 5 and ex 9.

```{r 5. predict g by lda, and visualize}
train$lda_predicted_class <- NULL
model5<-lda(g~.,data=train)
predict5<-predict(model5)
plot_data5<-data.frame(outcome=train$g,lda=predict5$x);#head(plot_data5)

ggplot(data=plot_data5,mapping=aes(x=lda.LD1,y=lda.LD2,color=outcome))+
  geom_point()
```

```{r 9.qda vs lda}
train$lda_predicted_class <- NULL
model9<-qda(g~.,data=train)

test %>%
  mutate(g=as.factor(g),qda_predicted_class=as.factor(predict(model9,newdata=test)$class)) %>%
  conf_mat(g,qda_predicted_class) %>%
  autoplot(type = "heatmap")

test %>%
  mutate(g=as.factor(g),qda_predicted_class=as.factor(predict(model9,newdata=test)$class)) %>%
  summarize(test_acc_qda=sum(g==qda_predicted_class)/nrow(test))%>%
  pull(test_acc_qda) ->test_acc_qda;test_acc_qda;test_acc
``` 

The following is my knitting window:

processing file: 02-lda-qda.Rmd
  |...                                                                   |   5%
  ordinary text without R code

  |.......                                                               |  10%
label: load-packages (with options) 
List of 2
 $ message: logi FALSE
 $ warning: logi FALSE

── Attaching packages ────────────────────────────────────── tidyverse 1.3.0 ──
✓ ggplot2 3.2.1     ✓ purrr   0.3.3
✓ tibble  2.1.3     ✓ dplyr   0.8.3
✓ tidyr   1.0.0     ✓ stringr 1.4.0
✓ readr   1.3.1     ✓ forcats 0.4.0
── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
── Attaching packages ───────────────────────────────────── tidymodels 0.0.3 ──
✓ broom     0.5.3     ✓ recipes   0.1.9
✓ dials     0.0.4     ✓ rsample   0.0.5
✓ infer     0.5.1     ✓ yardstick 0.0.5
✓ parsnip   0.0.5     
── Conflicts ──────────────────────────────────────── tidymodels_conflicts() ──
x scales::discard()   masks purrr::discard()
x dplyr::filter()     masks stats::filter()
x recipes::fixed()    masks stringr::fixed()
x dplyr::lag()        masks stats::lag()
x dials::margin()     masks ggplot2::margin()
x yardstick::spec()   masks readr::spec()
x recipes::step()     masks stats::step()
x recipes::yj_trans() masks scales::yj_trans()
  |..........                                                            |  14%
  ordinary text without R code

  |.............                                                         |  19%
label: 1.create-data-frame
  |.................                                                     |  24%
  ordinary text without R code

  |....................                                                  |  29%
label: 2.calculate lda score by hand
  |.......................                                               |  33%
  ordinary text without R code

  |...........................                                           |  38%
label: 3. use lda to verify

Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select

  |..............................                                        |  43%
  ordinary text without R code

  |.................................                                     |  48%
label: 4.load-data (with options) 
List of 1
 $ message: logi FALSE

Parsed with column specification:
cols(
  .default = col_double(),
  g = col_character()
)
See spec(...) for full column specifications.
Parsed with column specification:
cols(
  .default = col_double(),
  g = col_character()
)
See spec(...) for full column specifications.
  |.....................................                                 |  52%
  ordinary text without R code

  |........................................                              |  57%
label: 5. predict g by lda, and visualize

**Comment by LucyMcGowan** [comment]
@rachelmccrary and @LutionHan I just logged into your RStudio Cloud instances and both of your document knit for me.

@Feifan-990807 - if you email me your RStudio Cloud username so I can find your lab I'd be happy to take a look.

**Comment by emlines** [comment]
Hi @LucyMcGowan ... I think I'm having the same issue. It seems to be knitting without error, but then the document never pops up. Would you be able to check mine as well? Thanks

**Comment by LucyMcGowan** [comment]
If you already have it open, it is possible that it won’t pop up - you can double check that the .html file is updating by checking the date in the file pane and clicking on the file to see if the new changes held. Let me know if it looks like it is **not** updating and I’ll take a look 👀

**Comment by LutionHan** [comment]
Hi @LucyMcGowan, mine works now. Thanks!
PS. Although I still don't know why mine cannot knit yesterday...
