### ISSUE TITLE
Lab02 Ex 9

### ISSUE THREAD

**Issue by skywang0407** [sta-363-s20/community#23]
Hi Professor McGowan,
When I found the accuracy of the qda model on the train data, although the code works, it shows the accuracy as 1, which I believe is incorrect.
![Q3](https://user-images.githubusercontent.com/59891782/73977270-0d45f800-48f8-11ea-9abc-64d127344c4a.png)

How should I fix this?

Thanks！

**Comment by LucyMcGowan** [comment]
This is actually correct! In the training sample, QDA perfectly predicts the classes.

**Comment by skywang0407** [comment]
Got it, thanks!
