### ISSUE TITLE
Lab2 exercise9

### ISSUE THREAD

**Issue by Cindyyyhey** [sta-363-s20/community#25]
Dear Professor Lucy,

I'm working on exercise 9 about qda. I tried to fit the model for qda, but there is an error about "rank deficiency in group aa" in line 151. I’m not quite sure what that means.

Thanks a lot!

![9](https://user-images.githubusercontent.com/54655629/73996143-d50add80-4928-11ea-813a-48addd6bc791.jpg)

**Comment by skywang0407** [comment]
You may need to run the rsv chunk and the chunk where g is first predicted and then run the qda model again. Or, you may need to change the name of g when turn it to a factor to conduct the confusion matrix.

**Comment by juserrano** [comment]
Check the issue #26! She helped me out there by adding this line before you fit the model: 
train$lda_predicted_class <- NULL

**Comment by Cindyyyhey** [comment]
Thanks you @skywang0407  Let me try that!

**Comment by Cindyyyhey** [comment]
Thanks! @juserrano
