### ISSUE TITLE
Unable to knit

### ISSUE THREAD

**Issue by donaldwu0214** [sta-363-s20/community#28]
Hello Dr.McGowan,

When I am trying to finish Ex6, the R doesn't let me knit and I believe there is nothing wrong with the codes. Could you help me with the issue?

**Comment by LucyMcGowan** [comment]
Can you post the error that comes up when you try to knit?

**Comment by LucyMcGowan** [comment]
It’s possible you’re having the same issues as #26

**Comment by donaldwu0214** [comment]
Thank you so much, Dr. McGowan.
Do you know how to fix it?




| |
吴昊卿
邮箱：donaldwu0214@163.com
|

签名由 网易邮箱大师 定制

On 02/08/2020 15:12, LucyMcGowan wrote:

It’s possible you’re having the same issues as #26

**Comment by LucyMcGowan** [comment]
If it is the same issue, try what I propose here: https://github.com/sta-363-s20/community/issues/26#issuecomment-583772138

**Comment by donaldwu0214** [comment]
Thank you so much!!!!!!!!!!!!!!
