### ISSUE TITLE
Lab 02 Ex9

### ISSUE THREAD

**Issue by skyzhr621** [sta-363-s20/community#29]
I am quite confused that, for the QDA for training data, I get a misclassification rate of 0%. Is that correct or not for this data?
<img width="585" alt="Screenshot 2020-02-08 at 16 33 57" src="https://user-images.githubusercontent.com/59888385/74092377-d9eaa100-4a90-11ea-8659-ca4941d31b2f.png">

**Comment by juserrano** [comment]
I am getting the same thing. Have no idea if that's right either haha

**Comment by LucyMcGowan** [comment]
Looks okay to me - why do you think QDA may perfectly predict in the training data?

**Comment by emilyrandall5** [comment]
<img width="655" alt="Screen Shot 2020-02-09 at 12 07 52 PM" src="https://user-images.githubusercontent.com/59888484/74109039-d4469700-4b34-11ea-8aca-637e9e450bea.png">
I am confused because this is what I got for exercise 9, but it looks different from yours. Do you see any differences/problems with my code?

**Comment by skyzhr621** [comment]
> Looks okay to me - why do you think QDA may perfectly predict in the training data?



> <img alt="Screen Shot 2020-02-09 at 12 07 52 PM" width="655" src="https://user-images.githubusercontent.com/59888484/74109039-d4469700-4b34-11ea-8aca-637e9e450bea.png">
> 
> I am confused because this is what I got for exercise 9, but it looks different from yours. Do you see any differences/problems with my code?

**Comment by skyzhr621** [comment]
> <img alt="Screen Shot 2020-02-09 at 12 07 52 PM" width="655" src="https://user-images.githubusercontent.com/59888484/74109039-d4469700-4b34-11ea-8aca-637e9e450bea.png">
> 
> I am confused because this is what I got for exercise 9, but it looks different from yours. Do you see any differences/problems with my code?

I think you graph is correct and that is for the test one. The problem should include both a test and train.
