### ISSUE TITLE
Submit r.Rmd or knit document?

### ISSUE THREAD

**Issue by huqinyi0417** [sta-363-s20/community#3]
I followed all the instructions and now in my GitHub repo, I saw my r.Rmd updated. However I did not see the updated html report that I knitted in Cloud. Does it matter? @LucyMcGowan

**Comment by LucyMcGowan** [comment]
You can also commit and push the .html file by checking the box for that file in the Git pane in RStudio Cloud

**Comment by huqinyi0417** [comment]
> You can also commit and push the .html file by checking the box for that file in the Git pane in RStudio Cloud

Yes I clicked the box for the knit file in Cloud and push it for several times, but strangely GitHub repo still shows a html file which was 3 days ago......
