### ISSUE TITLE
Lab 02 - ex. 6 clarification

### ISSUE THREAD

**Issue by milljc17** [sta-363-s20/community#30]
Professor McGowan, 
I am a little confused as to how to use the predict function for ex. 6. ? I was hoping for a bit more clarification on what we are actually trying to find with the code snippet you provided us.
Best,
John

**Comment by LucyMcGowan** [comment]
In this exercise you are using the model you created using the `train` data and applying that model to a new data frame, `test`. This is done using the `predict()` function. This will output a list with three components - the one you are interested in is a vector called `class` that will identify the predicted class for each observation in the `test` data frame.
