### ISSUE TITLE
Lab 02 - EX 5

### ISSUE THREAD

**Issue by obranc97** [sta-363-s20/community#31]
For the visualization, are LD1 and LD2 the models we used in Exercise 3 and 5 respectively?

**Comment by LucyMcGowan** [comment]
No, these are the first two dimensions of the data reduction calculated from a single LDA model. 

* For more info about what is going on here see #27 
* For specifics on how to create this plot in R see the slides from Logistic, LDA, QDA Part 3

**Comment by obranc97** [comment]
Thank you, I am also having trouble committing and I am getting a message that says "Your branch is ahead of 'origin/master' by 1 commit" not sure what that means.

**Comment by LucyMcGowan** [comment]
Have you pushed it? That sounds like you need to push the commit.
