### ISSUE TITLE
Knitting problem

### ISSUE THREAD

**Issue by donaldwu0214** [sta-363-s20/community#32]
Hi Dr.McGowan,
I can't knit the html.
There are the issue and the relative chunk.

![image](https://user-images.githubusercontent.com/59888475/74107917-cc8def00-4b42-11ea-95ee-6482dbca26e5.png)

![image](https://user-images.githubusercontent.com/59888475/74107924-dc0d3800-4b42-11ea-9bd1-59d13c71faca.png)

**Comment by LucyMcGowan** [comment]
This looks like the same problem as we solved in #26 - take a look at those solutions, if they don’t work you can add additional comments there.
