### ISSUE TITLE
Lab 02 E6

### ISSUE THREAD

**Issue by harrisonpopp** [sta-363-s20/community#33]
For exercise 6 this is what I have so far and I'm not sure what I am missing or what the error code is telling me I need to change.
<img width="504" alt="Screen Shot 2020-02-09 at 1 51 00 PM" src="https://user-images.githubusercontent.com/59888399/74107992-5a69da00-4b43-11ea-93dc-ee64b8f142b9.png">

**Comment by LucyMcGowan** [comment]
This is not an error (although I see its confusing because it’s red!) it is actually just a message from the `read_csv()` function telling you how the columns were read in.

**Comment by midupree** [comment]
I was having this issue as well @LucyMcGowan , but my question is if we need any more code after this? I'm not getting anything outputted when I knit.
