### ISSUE TITLE
Knitting Issue

### ISSUE THREAD

**Issue by SangniHuang** [sta-363-s20/community#34]

**Comment by SangniHuang** [comment]
Hi Dr. McGowan.

I have a problem with knitting Lab 2 html and I have restarted Rstudio for a couple of times. Can you help me check what the issue is? Thank you!

![image](https://user-images.githubusercontent.com/59888391/74108209-e2e97a00-4b45-11ea-98fe-08d232558c52.png)
![image](https://user-images.githubusercontent.com/59888391/74108215-f4328680-4b45-11ea-93fc-386fda03705d.png)

**Comment by LucyMcGowan** [comment]
I just took a look and it knit for me 🤔

**Comment by DezhenMeng** [comment]
Hi Dr.McGowan,

Could you please also check mine? I knit my lab but it cannot reach 100% and generate the window for html file. I check my github and it seems the rmd file updated but the html file doesn't

**Comment by juserrano** [comment]
The same is happening to me. Always stopping at 60% and not showing that the html file updated.

**Comment by nuripark10** [comment]
Same! I am having the same issue at 57%.

**Comment by Iris-Liu-1212** [comment]
Same! Mine stopped at 75%.

**Comment by LucyMcGowan** [comment]
Can you all try to knit this morning and let me know if you are still seeing the issue?

**Comment by DezhenMeng** [comment]
I successfully knitted last night, thanks!

**Comment by nuripark10** [comment]
Got it!

**Comment by milljc17** [comment]
@LucyMcGowan 
Im having the same issue in which my knitting process stops at 57%. I was able to upload my completed rmd file to github, however, i cannot get the html to do the same. Was wondering if you had any suggestions?

**Comment by LucyMcGowan** [comment]
It seems like for most folks when this happens (if there aren’t any errors) giving it a bit of time and trying again seems to do the trick - let me know if it still isn’t working, though.

**Comment by milljc17** [comment]
@LucyMcGowan Ok I will keep trying to get the file to knit each hour up until the assignment is due, but so far no luck.

**Comment by milljc17** [comment]
@LucyMcGowan Nevermind, I was just able to get the file to knit completely. Still a little confused as to why giving it a bit time did the trick because there were no coding errors. Thanks for the help!

**Comment by LucyMcGowan** [comment]
Thank you for your persistence, everyone!
