### ISSUE TITLE
Interpreting #7

### ISSUE THREAD

**Issue by ZariahHawthorne** [sta-363-s20/community#35]
Dr. McGowan, 
I have plotted the confusion matrix, but how do I interpret the plot to know how the model performed? 

Thanks!

<img width="542" alt="Screen Shot 2020-02-09 at 6 32 19 PM" src="https://user-images.githubusercontent.com/58189250/74112417-83519580-4b6a-11ea-872e-905e524fa04b.png">

**Comment by LucyMcGowan** [comment]
Hi @ZariahHawthorne you can interpret the model performance by looking at the accuracy (the proportion that are on the diagonal divided by the total). The confusion matrix also helps you see which classes are getting mixed up by the model by looking at the off diagonals (for example, this model seems to be mixing up aa and ao classifications)
