### ISSUE TITLE
Lab 2 E8 + 9

### ISSUE THREAD

**Issue by msherrick** [sta-363-s20/community#37]
Hi @LucyMcGowan 

For exercises 8 and 9, I have a question on when it says to calculate the accuracy of the linear/quadratic discriminant analysis models. Are we using the misclassifcation percentage of the whole model or should we use the individual false positive and false negative rates obtained using the summarize() command?

**Comment by anishprasanna** [comment]
I think its the whole model. I just added up all the correct classifications and divided by the total number of observations. That gets accuracy, and you can subtract that from 1 to get misclassification error.

**Comment by msherrick** [comment]
@anishprasanna ok thank you! I was able to calculate that misclassification error percentage from the confusion matrix created with the test frame in exercise 7. So do I do the same thing with the train data frame now and compare?

**Comment by anishprasanna** [comment]
Yes, I think so. Also I believe we should be calculating accuracy instead of misclassification error.
