### ISSUE TITLE
Knitting freezes on a chunk but no error

### ISSUE THREAD

**Issue by traytib** [sta-363-s20/community#38]
Upon completing exercise 9 and trying to knit, my knitting now stops on my exercise 5 chunk even though I didn't change anything in that chunk. There's no error and all the chunks run individually. Any ideas?

<img width="463" alt="Screen Shot 2020-02-10 at 5 16 18 PM" src="https://user-images.githubusercontent.com/59888442/74195372-12bd7e00-4c29-11ea-9cec-613a30bc3794.png">

<img width="521" alt="Screen Shot 2020-02-10 at 5 15 16 PM" src="https://user-images.githubusercontent.com/59888442/74195309-f15c9200-4c28-11ea-9712-b8694bf6a456.png">

**Comment by traytib** [comment]
My bad did not notice there is already a thread for this.

**Comment by LucyMcGowan** [comment]
I think this is related to #34
