### ISSUE TITLE
Local Git Branch behind Master Branch 

### ISSUE THREAD

**Issue by tkinsella333** [sta-363-s20/community#39]
Hi Professor, 

I had to copy and paste new code to git and update my file on the actual github.com website as r studio cloud wasn't working for me. I hope this is ok, as I couldn't get my final commits to work out after updating on the github website as my local branch in r studio was behind my master branch on github.com

I assume this isnt a problem in terms of turning in my final work -- i.e as long the file is in my github repo on github.com it should be ok right? 

Thanks! 
Tim

**Comment by LucyMcGowan** [comment]
Yes, as long as the correct files are on GitHub you should be ok. Here is some reading on fixing / troubleshooting when your local branch is behind GitHub in case you find yourself in this situation again:

https://happygitwithr.com/pull-tricky.html
