### ISSUE TITLE
Lab 02 Knitting problem

### ISSUE THREAD

**Issue by midupree** [sta-363-s20/community#40]
@LucyMcGowan 
My lab was working great until this evening! It is knitting until about 62%, then it will stop. It won't show an error, but I'm a bit worried.

Also, a new error popped up with the Ex. 6 that is also showing up everytime I use this line of code. 

model <- lda(g ~ ., data = train)

<img width="587" alt="Screen Shot 2020-02-10 at 8 05 40 PM" src="https://user-images.githubusercontent.com/59888424/74204338-c1b98400-4c40-11ea-9b17-53186a907aad.png">

Not sure what to do, as this issue just started happening. Everything was working great before, just came up when I was going over my lab.
Thanks

**Comment by LucyMcGowan** [comment]
This looks similar to #26 - the problem is with the train data. You need to either drop any columns added or just re -load from the csv (you reload the test data in your code, switch that to train)

**Comment by midupree** [comment]
Awesome! That fixed it, but now this issue is popping up? It's like one thing after another!

<img width="550" alt="Screen Shot 2020-02-10 at 9 19 12 PM" src="https://user-images.githubusercontent.com/59888424/74206828-0ea25800-4c4b-11ea-9e3e-55fb8e7863bc.png">

I'm going to check some other questions to see if anyone else had this issue. Thanks again.
