### ISSUE TITLE
R Code of cross validation

### ISSUE THREAD

**Issue by Cindyyyhey** [sta-363-s20/community#41]
Dear Professor @LucyMcGowan 

I understand the concept of cross validation, but I'm so confused about how to do cross validation and K-fold thing in R. Could you explain those R code for calculating k-fold cross validation and in-class exercise again on tomorrow's class?

Thanks!

**Comment by LucyMcGowan** [comment]
## Step 1: Shuffle the data frame and add a variable `k` that indicates the group

Here is an example of some R code to do this. Here `k` is 5.
```
K <- 5
df <- df %>%
  slice(sample(1:nrow(df))) %>% ## shuffle the data
  mutate(k = rep(1:K, length.out = nrow(df))) ## add a variable, k that indicates which group they are in (from 1 to 5)
```

## Step 2: Fit a model with all data leaving out group `k`, then calculate the "test" MSE using group `k`

We can split this step into 3 subsets:
a. Create a data frame with all the data (minus group `k`)
b. Fit a model on this data frame
c. Calculate the test MSE using the `k` group that was left out of the model fitting

Here is a function that completes each of these steps.

```
mse_k <- function(K = 1) {
 ## step 2a. Create a data frame that filters out (removes) group k
  df_k <- df %>% 
    filter(k != K) 
## step 2b. Fit a model to this reduced data frame
  model_k <- lm(y ~ x, data = df_k)
## step 2c. Create a data frame with ONLY group p. Calculate the MSE using the model created in step 2b.
  df %>%
    filter(k == K) %>% 
    mutate(p = predict(model_k, newdata = .)) %>%
    summarise(mse_k = mean((y - p)^2),
              n_k = n())
}
```

## Step 3. Iterate from 1:K over this function that performs these steps, then summarize the results to get the overall K-fold Cross Validation Error

```
## Iterate from 1:K
map_df(1:K, ~ mse_k(.x)) %>%
  summarise(cv_5 = sum(n_k / sum(n_k) * mse_k)) ## calculate the CV error
```

**Comment by Cindyyyhey** [comment]
Thank you so much for the explanation! One more question: Do we need to know the detail R syntax such as  (1:nrow(df) rep(1:K, length.out = nrow(df) means? Or we just need to understand what each steps do in R? @LucyMcGowan
