### ISSUE TITLE
Test Corrections - Question 2

### ISSUE THREAD

**Issue by emilyrandall5** [sta-363-s20/community#46]
For part c, does anyone know what the decision boundary means in terms of how to classify a new observation with a particular age? I got 34.7 for the boundary value.

**Comment by LucyMcGowan** [comment]
When I did it I got something around 35.15 (but maybe there is a rounding error?) Here is my R code to check the work. 

```
d <- data.frame(y = rep(c("enjoy ewoks", "hate ewoks"),  times = c(3, 4)),
                age = round(c(rnorm(3, 37, 20), rnorm(4, 55, 20)), 2))
d %>% 
  group_by(y) %>%
  summarise(mu = mean(age)) %>%
  pull() -> mu
d %>%
  group_by(y) %>%
  summarise(nk = n(),
            vark = var(age)) %>%
  mutate(v = (nk - 1) / (sum(nk) - 2) * vark) %>%
  summarise(sum(v)) %>%
  pull() -> sigma
d %>%
  group_by(y) %>%
  summarise(n = n()) %>%
  mutate(n / sum(n)) %>% pull() -> pi

(mu[1]^2 / (2 * sigma) - log(pi[1]) - mu[2]^2 / (2 * sigma) + log(pi[2])) / (mu[1] / sigma - mu[2] / sigma)
```

The decision boundary means the age at which you'd switch your classification, so if I saw a new observation with an age less than 35.15 I'd say they Enjoy Ewoks, if I saw a new observation older than 35.15, I'd predict they Hate Ewoks.
