### ISSUE TITLE
Lab 3 Ex 3/4 - error for object 'k'

### ISSUE THREAD

**Issue by awiggin** [sta-363-s20/community#48]
Hi Professor McGowan,

I'm having trouble when knitting exercise 4. I can run each code chunk and it gives me MSE values for each model. But when I knit the document, I get an error message for line 46. I've deleted the code on lines 46 and 47, as well as placing a # next to them like in the photo, but I get the same error message when knitting. Any thoughts on how I can fix this?

Thanks!  

<img width="687" alt="Screen Shot 2020-02-24 at 1 14 44 PM" src="https://user-images.githubusercontent.com/16576384/75179405-faa92c80-5707-11ea-8b9e-d46aa6747de9.png">

**Comment by LucyMcGowan** [comment]
The problem is line 49 & 50 - you are filtering where `k==1`, but the column `k` does not exist in the `Auto` data frame (it is in the `Auto_2` data frame you created in the chunk above). Change `Auto` to `Auto_2`.  Then you want to have a NEW name for your training data, something like

```
train <- Auto_2 %>%
  filter(k != 1)
model1 <- lm(mpg ~ horsepower, data = train)
```

**Comment by awiggin** [comment]
Great makes more sense, thank you!
