### ISSUE TITLE
Exercise 6 - output function into data frame

### ISSUE THREAD

**Issue by juserrano** [sta-363-s20/community#49]
<img width="960" alt="2020-02-24 (1)" src="https://user-images.githubusercontent.com/59888434/75182257-faac2b00-570d-11ea-92ba-2df7ca75a6dc.png">
I am having issues outputting the data frame for exercise 6. I have tried some variations of the code, and even the basic data frame code we used in previous labs but I always get this error:
Error in summarise(mse_1, mse_2, mse_3, n_k = n()) : object 'mse_1' not found

Does anyone know what the proper code is?

**Comment by LucyMcGowan** [comment]
You can combine lines 87-97 by having `p1` `p2` and `p3` all created in the same mutate call and `mse_1` `mse_2`and `mse_3` all created in the same summarise like this:

```
Auto_2 %>%
  filter(k ==k) %>% 
  mutate(
     p1 = ---,
     p2 = ---,
     p3 = ---
  ) %>%
  summarise(
    mse_1 = ---,
    mse_2 = ---,
    mse_3 = ---,
    n_k = n()
)
```

**Comment by juserrano** [comment]
Thank you! That worked out!

**Comment by midupree** [comment]
@LucyMcGowan I am having a similar issue, but that object (k) is not found. I took the advice you gave above and implemented it in my coding. Here is the full rundown:
<img width="474" alt="Screen Shot 2020-02-26 at 12 26 48 PM" src="https://user-images.githubusercontent.com/59888424/75370622-62d84980-5893-11ea-840e-07a87c0e0733.png">
