### ISSUE TITLE
Lab01

### ISSUE THREAD

**Issue by skywang0407** [sta-363-s20/community#5]
Hi Professor McGowan,
I have two questions as below:
1. Can I describe the plot of 2005 as "the positive correlation between day and volume" as the picture below?
![Q1](https://user-images.githubusercontent.com/59891782/72762224-d6a87780-3bac-11ea-9e0e-c82ce9a3e97a.png)

2. I have seen all my commits pushed and the status on my Github of Lab01 shows "Lab01 is done!" as the description I added to the dialogue. Is everything done or do I need to submit the HTML I export again to Canvas?

Thanks!

**Comment by LucyMcGowan** [comment]
1. Yes
2. You do not need to submit the .html file to Canvas, but you should make sure to commit and push the .html file to GitHub as well as the .Rmd file.
