### ISSUE TITLE
Ex. 6

### ISSUE THREAD

**Issue by midupree** [sta-363-s20/community#52]
@LucyMcGowan I mentioned you a few hours ago in one of the past feeds but I didn't get a response, so I thought it might be best to create my own thread.
My code works except it says "object k not found". Here is my code.
<img width="678" alt="Screen Shot 2020-02-26 at 12 26 27 PM" src="https://user-images.githubusercontent.com/59888424/75392056-43ecae00-58b9-11ea-9676-319bb1e22f18.png">

**Comment by midupree** [comment]
Sorry, I meant to insert the full picture. It is here
<img width="474" alt="Screen Shot 2020-02-26 at 12 26 48 PM" src="https://user-images.githubusercontent.com/59888424/75392124-6383d680-58b9-11ea-95c3-5c05433386a1.png">

**Comment by LucyMcGowan** [comment]
this is similar to #48. There are a few things:

1. Move the chunk:
```
Auto_2 <- Auto %>%
 slice(...
Auto_2 %>%
  group_by() %>%
  summarise()
```
to outside the function.

2.the parameter you are varying in your function is set by what you have in parenthesis (in this case `K`) - R is case sensitive so you need to use a capital `K` when you refer to it in your code. there are two places that need to be fixed, `filter(k == k)` should be `filter(k == K)` and `filter(k != 1)` should be `filter(k != K)`

**Comment by midupree** [comment]
Thank you @LucyMcGowan!
However, now I am getting a new error, which is that my X and Y differ.
Is there any particular place I should be looking to fix this?

<img width="629" alt="Screen Shot 2020-02-26 at 5 26 01 PM" src="https://user-images.githubusercontent.com/59888424/75393945-215c9400-58bd-11ea-9ea1-90d32a7026eb.png">

**Comment by LucyMcGowan** [comment]
You have an extra summarise function that you don't need (the line right before the final } can be deleted)

**Comment by midupree** [comment]
@LucyMcGowan I got rid of that line, the:

  summarise(mse_1, mse_2, mse_3, n_k)

yet it's still giving me the same error. So sorry to keep on bothering

**Comment by LucyMcGowan** [comment]
You have a typo in your third model, should be `poly` not `plot`

**Comment by midupree** [comment]
@LucyMcGowan I am going through and double checking all of my code, but here is what I have that is still giving me an error.
Thanks so much

<img width="629" alt="Screen Shot 2020-02-26 at 5 26 01 PM" src="https://user-images.githubusercontent.com/59888424/75394583-6d5c0880-58be-11ea-9503-fba8b01febf6.png">

**Comment by LucyMcGowan** [comment]
You have the same typo in model3 you have `plot(horsepower, 3)` should be `poly(horsepower,3)`
Also, you still have the `summarise(mse_1, mse_2, mse_3, n_k)` at the end of your function (maybe you posted an old screenshot?)

**Comment by midupree** [comment]
@LucyMcGowan 
Wait yes I am so sorry I totally posted the wrong one.

<img width="652" alt="Screen Shot 2020-02-26 at 5 35 41 PM" src="https://user-images.githubusercontent.com/59888424/75395078-9d57db80-58bf-11ea-8aa4-4f3a470f8c04.png">

**Comment by LucyMcGowan** [comment]
Now you have the same error twice! Should be `poly` NOT `plot`

**Comment by midupree** [comment]
Oh my gosh, I can't believe myself. Thank you for being so patient!

**Comment by LucyMcGowan** [comment]
Don’t worry! Debugging is often a painful process (and easier to spot in someone else's code!)
