### ISSUE TITLE
Exercise 7

### ISSUE THREAD

**Issue by ZariahHawthorne** [sta-363-s20/community#53]
Hi @LucyMcGowan 
I am getting this error for exercise 7. Am I missing some code?
<img width="486" alt="Screen Shot 2020-02-26 at 5 36 03 PM" src="https://user-images.githubusercontent.com/58189250/75394623-84025f80-58be-11ea-9a55-2c7b1c0ce408.png">

**Comment by midupree** [comment]
I had this issue too

**Comment by LucyMcGowan** [comment]
The most likely problem is where you have `sum(n_k) * mse_K` should be `* mse_1` (or whatever you call your mse column.  You will have 3 of these since you have 3 mse, one for each model.
