### ISSUE TITLE
Exercise 6

### ISSUE THREAD

**Issue by walkerjohn97** [sta-363-s20/community#54]
Hey Dr. McGowan, 

I'm having problems with exercise 6. I based my codes off the code in the slides and the code runs without any errors, but the MSE is the same for all 3 models, so something is wrong. I paste
 code below

<img width="803" alt="Screen Shot 2020-02-26 at 7 13 56 PM" src="https://user-images.githubusercontent.com/59891793/75400197-88ce1000-58cc-11ea-91fe-e54d60fd92f3.png">

**Comment by LucyMcGowan** [comment]
You should have 3 model statements (instead of having poly vary with k, you should just have 3 separate lines in there) check out the code in #49 along with my response there.

**Comment by walkerjohn97** [comment]
If I change the k in that line to K, i get 3 mse's. Does that work?

**Comment by walkerjohn97** [comment]
<img width="732" alt="Screen Shot 2020-02-26 at 8 43 20 PM" src="https://user-images.githubusercontent.com/59891793/75404534-db152e00-58d8-11ea-95ea-483ae6b4e74e.png">

Using this code I get different MSE's, but i do not have 3 model statements. Is this wrong?

**Comment by LucyMcGowan** [comment]
You should have 3 different MSEs (1 for each model) yes, but the code above is _wrong_. You are using K 2 times in that code, once to determine the fold of data that is left out of the training model (and then used to calculate the MSE) **this is correct!** and once to pick the polynomial term **this is not correct**! You should have 3 separate model statements, 3 separate predicted values, and 3 separate MSEs
