### ISSUE TITLE
Lab4 Exercise 3-5

### ISSUE THREAD

**Issue by SangniHuang** [sta-363-s20/community#55]
Hi Dr. McGowan,

For using tone to find penalty and mixture, can we set the penalty to go up by 1 instead of 10? For the elastic net model, can we set mixture to 1 or it has to be (0,1) exclusive?

Thank you!

**Comment by LucyMcGowan** [comment]
Yes, you can set the penalty to go up by 1. You can set the mixture to 1 (that would just be Lasso)
