### ISSUE TITLE
package"glmnet"

### ISSUE THREAD

**Issue by AliceCaiAC** [sta-363-s20/community#57]
@LucyMcGowan @sarahrenfrow 
Hi Dr. McGowan,

I can't use Rstudio-pro outside the campus, and the RStudio Cloud doesn't have version 3.6.2, so I can't install the glmnet package... What should I do?

Thank you!

**Comment by nuripark10** [comment]
I was able to install it by typing "install.packages("glmnet", dependencies=TRUE)" on terminal!

**Comment by AliceCaiAC** [comment]
@nuripark10 Thank you! It worked!
