### ISSUE TITLE
About Lab 4

### ISSUE THREAD

**Issue by QimingFangS** [sta-363-s20/community#60]
Hello Dr. McGowan, 

I am working on Lab 4 and I have the following questions.

1. When I tried to get the test RMSE for lasso, I found that if set the range of λ to 0-100, there would be little difference in the resulted test RMSE. Thus, I changed the range of λ to 0-10 instead which works fine. I am wondering if we can adjust the range like that.

2. When I calculate the test RMSE of ridge regression, everything works fine. However, when it comes to lasso and elastic net, R Markdown produced warning as indicated on the image, but nothing goes wrong on the output html file. I am wondering if we need to worry about this issue.
![error](https://user-images.githubusercontent.com/52064608/77240514-efd5a080-6bbc-11ea-86b6-0eabc70b0811.JPG)

3. For Question 6, we were asked how accurate the models are. However, based on the test RMSE, we can only compare the accuracy of models. I am not sure whether we need to explain how accurate each individual model is. And if we need to explain them, how we are supposed to do so.

Thank you very much!

**Comment by jdtrat** [comment]
For number 2, see #56. Dr. McGowan said to ignore the fold errors.

**Comment by LucyMcGowan** [comment]
1. Yes, that is fine
2. Thank you @jdtrat! Yes, look at #56 for a discussion on this
3. For 6, I just mean for you to discuss the results for the previous questions and summarize how well the model fit (as in discuss the RMSE and/or R-squared values) but the word _accuracy_ here is not so precise (sorry!). I would count this answer as **correct** if you explain what the RMSE or R-squared (or both!) are summarizing and state what it is for the best model.
