### ISSUE TITLE
Lab 4 

### ISSUE THREAD

**Issue by harrisonpopp** [sta-363-s20/community#61]

**Comment by harrisonpopp** [comment]
What am I doing wrong to get this error response for Q3? I'm trying to use tune to get the lambda I want to use to get the lowest rmse.

<img width="505" alt="Screen Shot 2020-03-23 at 12 24 37 PM" src="https://user-images.githubusercontent.com/59888399/77338786-36341800-6d01-11ea-828a-604d6d5adbc0.png">

**Comment by LucyMcGowan** [comment]
I think this is related to #57 - check out Nuri’s answer there

**Comment by harrisonpopp** [comment]
I ran that code in the terminal and I'm still getting the same error, is this because I am on rstudio cloud?

**Comment by LucyMcGowan** [comment]
Did you run it in the console? 

```
install.packages("glmnet")
```
