### ISSUE TITLE
Lab 4 Interpretation help

### ISSUE THREAD

**Issue by midupree** [sta-363-s20/community#62]
@LucyMcGowan I am having some issues sorting out the interpretation questions, probably because I am trying to refamiliarize myself with the material. I did most of my coding before I left for break and have been struggling to remember what does what and how I did it! For example, where do we find our chosen lambda and the test root mean squared error? 
I've attached my coding for question 4 as a reference. Once I understand what I did I'm sure I'll be ready to continue on with the other questions!
Thanks,
Miriam

<img width="663" alt="Screen Shot 2020-03-23 at 12 31 55 PM" src="https://user-images.githubusercontent.com/59888424/77339591-629c6400-6d02-11ea-8f95-78076aa5d38b.png">
<img width="632" alt="Screen Shot 2020-03-23 at 12 31 48 PM" src="https://user-images.githubusercontent.com/59888424/77339595-6334fa80-6d02-11ea-80fb-c525b8894c78.png">

**Comment by LucyMcGowan** [comment]
Penalty is your lambda value. Mean is the average RMSE for each penalty

**Comment by midupree** [comment]
@LucyMcGowan so do I need to report each Mean? Or just average them?

**Comment by LucyMcGowan** [comment]
The instructions are to report the penalty that gives the best (smallest) RMSE, so just report that one.

**Comment by midupree** [comment]
Thank you @LucyMcGowan!
So with Tune as our set penalty, that allows us to vary our lambda values, testing potentials of 0 and 10? That is what I interpreted from the slides.

**Comment by midupree** [comment]
@LucyMcGowan Would we report our chosen lambda value as varying between 0-10? Just need to fully understand this before I turn in my lab. I couldn't find much information about it in the tidy models slides.
Thanks

**Comment by LucyMcGowan** [comment]
Yes! Sorry I missed your question before
