### ISSUE TITLE
Ex 3+4

### ISSUE THREAD

**Issue by msherrick** [sta-363-s20/community#63]
Hi @LucyMcGowan ,

For both ridge regression and lasso, whenever I run the code, I get different results for the table with the RSME and penalties each time. I set a seed to fix it but I noticed that I get different results based on the seed I set. Below is my code for exercise 3, with exercise 4 being similar apart from the change in mixture with the linear_reg command. 

music_cv <- vfold_cv(music_train, v=10)

rec <- recipe(lat ~., data=music_train) %>%
  step_scale(all_predictors())

ridge_reg <- linear_reg(penalty = tune(), mixture = 0) %>%
  set_engine("glmnet")

grid <- expand_grid(penalty = seq(0, 10, by = 1))
  
results <- tune_grid(ridge_reg,
                     preprocessor = rec,
                     grid = grid,
                     resamples = music_cv)

results %>%
  collect_metrics() %>%
  filter(.metric == "rmse") %>%
  arrange(mean)

Is there something wrong with my code, or is there a specific seed you want us to set. Let me know, thank you!

**Comment by LucyMcGowan** [comment]
Yes! Youll get slightly different answers depending on the seed - I think I requested in the lab that you set it to 7?

**Comment by msherrick** [comment]
Thank you! One more quick follow up question, can we assume the collect_metrics() command with metric=="rmse" is computing the test root mean squared error, or is it the training RMSE?

**Comment by LucyMcGowan** [comment]
Depends which model your using it on. For example an object created using the `last_fit()` function will automatically use the test data when calculating the metric

**Comment by msherrick** [comment]
So last question, if I am using the following last_fit() command:
```
final_spec <- linear_reg(penalty = 6, mixture = 0) %>%
  set_engine("glmnet")
fit <- last_fit(final_spec,
                rec,
                split = music_split)
fit %>%
  collect_metrics()
```
where music_split <- initial_split(music, prop = 0.5), is this using the test or training data from the split, or does it not matter as it is computing the test RMSE regardless?

**Comment by jdtrat** [comment]
@msherrick I believe the `last_fit()` function automatically uses the test data from the `music_split` object which is how it can calculate the test root mean squared error.

**Comment by msherrick** [comment]
appreciate it thank you

**Comment by michaeljurgens** [comment]
<img width="620" alt="Screen Shot 2020-03-24 at 12 08 54 PM" src="https://user-images.githubusercontent.com/59888451/77449532-698daa00-6dc8-11ea-8c4a-bb88fec3f731.png">
Hi @LucyMcGowan , I keep getting this error and can't figure out why.  Isn't 'ridge_spec' a formula?

**Comment by jdtrat** [comment]
@michaeljurgens go look at #58
