### ISSUE TITLE
Welcome video

### ISSUE THREAD

**Issue by skywang0407** [sta-363-s20/community#64]
Hi Lucy,
When I try to access the Welcome video, it is not found on Youtube and the slide icon also cannot get to the lecture. 

Can you please check them?

Thanks!
![404](https://user-images.githubusercontent.com/59891782/77378249-ec245400-6d4b-11ea-8429-adf0f3233549.png)
![Video not found](https://user-images.githubusercontent.com/59891782/77378250-ecbcea80-6d4b-11ea-8797-590b29d286be.png)

**Comment by LucyMcGowan** [comment]
You caught me a bit early - the video is still uploading! It should be set by class time tomorrow for sure (likely before!)

**Comment by skywang0407** [comment]
Got it! I am sorry that I ask this too early, since I am a little bit anxious about our future remote learning. 
Anyway, thank you a lot!

**Comment by LucyMcGowan** [comment]
No need to be sorry! 🤗
