### ISSUE TITLE
Lab 4 Elastic Model

### ISSUE THREAD

**Issue by donaldwu0214** [sta-363-s20/community#66]
Hello Dr. McGowan.
For the lab4 Exercise 5, I have found out that the elastic model with the smallest RMSE is the same model as the lasso model. So can the mixture of the elastic model be 1, which indicates that the elastic model to be exactly same as the lasso model?

![image](https://user-images.githubusercontent.com/59888475/77471303-6acecf00-6de8-11ea-8a8f-54737eafd34d.png)

**Comment by LucyMcGowan** [comment]
Sort of! In the case of exactly 0 (ridge) or exactly 1 (lasso) I would probably not call it "elastic net" but rather ridge or lasso. But for the purposes of this question, since you tried mixtures between 0 and 1, you were performing elastic net for the values in between (so this looks good to me)

**Comment by donaldwu0214** [comment]
In another word, I can pick mixture  = 1 as the elastic model for this question, right?

**Comment by LucyMcGowan** [comment]
yep, that is fine :+1:

**Comment by donaldwu0214** [comment]
Thank you!
