### ISSUE TITLE
Ex 3 Lab 5

### ISSUE THREAD

**Issue by midupree** [sta-363-s20/community#67]
@LucyMcGowan I had a quick question on Number 3!
I'm getting a little confused on the second part, which asks us to fit age using a natural spline. Use tune() to decide how many degrees of freedom to use for the age variable.
I think I got the first part of creating a recipe, but I'm having trouble understanding how to use the natural spline. I've been searching through the slides with no avail. Is there any place I should look for reference to help me solve this problem?
Here is what I have so far:

<img width="766" alt="Screen Shot 2020-03-25 at 7 32 49 PM" src="https://user-images.githubusercontent.com/59888424/77595459-97a9e180-6ecf-11ea-8a15-36f0d1e8455a.png">

Thanks so much for all you do,
Miriam

**Comment by LucyMcGowan** [comment]
The slides from class on Tuesday show you how to use the natural spline with `step_ns`. The code you have there is doing penalized regression, this should just be regular linear model (using lm as the engine)

**Comment by msherrick** [comment]
Hi @LucyMcGowan,

I also have a question on this exercise. I used the following code to create my recipe: 
```
wage_recipe <- Wage %>%
  recipe(wage ~ age, health_ins, jobclass, education, race) %>%
  step_ns(age,deg_free = tune())

wage_recipe
```
![Screen Shot 2020-03-25 at 8 35 25 PM](https://user-images.githubusercontent.com/59072967/77598455-3d614e80-6ed8-11ea-9560-9d219fa3cfb0.png)

Is this output giving me the degrees of freedom, such that I would say that we would use 1 degree of freedom for age (the predictor row)?

**Comment by LucyMcGowan** [comment]
That is the correct recipe. Now you need to do cross validation & tune the model to get the degrees of freedom

**Comment by midupree** [comment]
@LucyMcGowan Okay so I was able to create a recipe and have the same question. For cross validation, would we use the coding from the cross-validation slides? I've attached. Would this give us the degrees of freedom once we incorporate the tune function?
<img width="725" alt="Screen Shot 2020-03-26 at 12 10 00 PM" src="https://user-images.githubusercontent.com/59888424/77669128-bf925700-6f5a-11ea-80e9-29a37f49d9b6.png">

**Comment by michaeljurgens** [comment]
Hi @LucyMcGowan I had exercise 3 working yesterday but today when I try to run it I'm getting this error and I'm not sure what it means, I didn't change any of the code from when it was running
<img width="611" alt="Screen Shot 2020-03-26 at 12 52 33 PM" src="https://user-images.githubusercontent.com/59888451/77673643-d2a82580-6f60-11ea-8eaf-b16f66d5c934.png">

**Comment by LucyMcGowan** [comment]
@midupree no, for cross validation you can use similar code that you used in lab 4 (incorporating vfold_cv with tune_grid)

**Comment by LucyMcGowan** [comment]
@michaeljurgens hmmm that is strange - can you try restarted your R session? (In the menu bar click Session > Restart R )

**Comment by midupree** [comment]
So I noticed that this may actually be the coding for question 4, but I am 
1. not sure whether I've actually answered question 3
2. not sure how to fix this problem.
I double checked with the other thread and I made all the same corrections as them to fix the model failure.

<img width="738" alt="Screen Shot 2020-03-26 at 3 17 10 PM" src="https://user-images.githubusercontent.com/59888424/77687595-0a20cd00-6f75-11ea-8cb0-352882b24810.png">

**Comment by msherrick** [comment]
I am also unsure if I have answered exercise 3 completely. In response to your last comment, are you just looking for the recipe in exercise 3, and then using tune to "decide how many degrees of freedom to use for the age variable" through cross validation and tuning the model all in exercise 4?

**Comment by LucyMcGowan** [comment]
* Yes, 3 is just the recipe 👍 
* Skip the data splitting above, just create the cross validation object from the whole data set (`Wage` instead of `wage_train`)
* I’m not sure what `penalty_spec` is. Exercise 2 asked you to specify `linear_spec` that’s what you should use here 
* what is your `grid`

**Comment by midupree** [comment]
I think my main problem is understanding how to get the degrees of freedom. My recipe coding said the same as Matt's above, 1 for the outcome and the penalty.
I've altered my question 4, but it is outputting zero rows. Not sure what is going on but I assume it has to do with my confusion before.

<img width="745" alt="Screen Shot 2020-03-26 at 6 21 53 PM" src="https://user-images.githubusercontent.com/59888424/77702352-b28f5b00-6f8e-11ea-8c16-a4847f3e812c.png">

**Comment by midupree** [comment]
@LucyMcGowan I think I may have finally figured it out; Would we take the lowest rmse and then report the degrees of freedom listed there? 

<img width="738" alt="Screen Shot 2020-03-26 at 6 30 51 PM" src="https://user-images.githubusercontent.com/59888424/77702987-19614400-6f90-11ea-8b0c-4e20dceec7b2.png">

<img width="739" alt="Screen Shot 2020-03-26 at 6 30 57 PM" src="https://user-images.githubusercontent.com/59888424/77702993-1c5c3480-6f90-11ea-9076-008164662615.png">

**Comment by LucyMcGowan** [comment]
Yes exactly!

**Comment by midupree** [comment]
@LucyMcGowan Is there a difference between the rsq and rmse? Or do I just need to choose the model with the lowest value that is labeled rmse?

**Comment by LucyMcGowan** [comment]
Yes, `rsq` is R-squared, `rmse` is the root mean squared error. You should use `rmse` for this.
