### ISSUE TITLE
question about tidymodels

### ISSUE THREAD

**Issue by Iris-Liu-1212** [sta-363-s20/community#69]
Hi Dr. McGowan @LucyMcGowan ,

I wonder if prop = 0.4 here, does it mean training data takes 40% percent of the observations or testing data takes 40% percent of the observations?
![tidymodel](https://user-images.githubusercontent.com/54609373/77859014-ef4c9380-71d4-11ea-8e8b-4c52a9a2f187.jpeg)
Thanks!

**Comment by jdtrat** [comment]
`prop` is the proportion of training data. Documentation for that function can be found [here](https://www.rdocumentation.org/packages/rsample/versions/0.0.5/topics/initial_split)

**Comment by LucyMcGowan** [comment]
Thanks @jdtrat! That is correct!
