### ISSUE TITLE
cubic spline degrees of freedom

### ISSUE THREAD

**Issue by Cindyyyhey** [sta-363-s20/community#71]
![屏幕快照 2020-03-31 上午12 27 45](https://user-images.githubusercontent.com/54655629/77987525-092acb00-72e8-11ea-8b4d-76ade10238dd.png)
Hi Professor McGowan!
Since we know that cubic spline with k knots have k+4 degrees of freedom, we have 3+4=7 degrees of freedom in total. 6 are used for horsepower variable and 1 df used for weight variable . Why don't we need to count the df of intercept here?

**Comment by LucyMcGowan** [comment]
Yes there are 6 for horsepower, 1 for the intercept (that’s k+4) and 1 for weight, so 8 total for everything in the model.

**Comment by Cindyyyhey** [comment]
Got it, Thanks!
