### ISSUE TITLE
Image for Plot

### ISSUE THREAD

**Issue by midupree** [sta-363-s20/community#73]
@LucyMcGowan, for some reason my final plot looks like this and I cannot figure out how to fix it! I've included my above coding for this week. Let me know if you need a different line of coding for reference.
Thanks,
Miriam
<img width="605" alt="Screen Shot 2020-04-08 at 10 08 06 AM" src="https://user-images.githubusercontent.com/59888424/78793822-f1ef7b80-7980-11ea-9221-78e13be1826a.png">
<img width="599" alt="Screen Shot 2020-04-08 at 10 08 13 AM" src="https://user-images.githubusercontent.com/59888424/78793866-fe73d400-7980-11ea-957e-f00be5a4d7c7.png">

**Comment by LucyMcGowan** [comment]
Ah that likely means your cost complexity basically doesn’t allow for any nodes to be created - what did your final alpha (cost) come to?

**Comment by midupree** [comment]
@LucyMcGowan  
Would that be found under 
model %>%
  select_best(metric = "rmse")

Because then it would be .05

**Comment by LucyMcGowan** [comment]
Ah yes, try setting the cost_complexity to 0 to see if that changes it
