### ISSUE TITLE
Installing R Plot

### ISSUE THREAD

**Issue by walkerjohn97** [sta-363-s20/community#74]
Hey Dr. McGowan, 

I'm having trouble installing r plot. I attached screenshots of my code.

<img width="687" alt="Screen Shot 2020-04-08 at 10 44 53 AM" src="https://user-images.githubusercontent.com/59891793/78797911-57923680-7986-11ea-818e-a25a83c9a672.png">
<img width="691" alt="Screen Shot 2020-04-08 at 10 45 00 AM" src="https://user-images.githubusercontent.com/59891793/78797920-5a8d2700-7986-11ea-9a10-5a70217366ff.png">

**Comment by walkerjohn97** [comment]
I figured out the problem!

**Comment by LucyMcGowan** [comment]
In case anyone else runs into this, FALSE needs to be all caps 👍
