### ISSUE TITLE
Final Step for Random Forest

### ISSUE THREAD

**Issue by midupree** [sta-363-s20/community#75]
@LucyMcGowan I'm getting a strange error with my last chunk of coding. Any idea how I can fix?
Also, It says I have to install the "ranger" package for my model.
Thanks,
Miriam
<img width="591" alt="Screen Shot 2020-04-10 at 10 44 18 AM" src="https://user-images.githubusercontent.com/59888424/78999327-601a7680-7b18-11ea-9fc0-3b1d1b727220.png">

**Comment by jdtrat** [comment]
Hi @midupree, to fix the ranger package, in the console just type `install.packages("ranger")`. For the chunk of code pictured here, Dr. McGowan said we don't need to plot a confusion matrix since it is for regression data; they are only used for categorical data.
