### ISSUE TITLE
Bagging Question 

### ISSUE THREAD

**Issue by tkinsella333** [sta-363-s20/community#78]
In the Bagging lecture you go over: "If we have a set of n independent observations: Z_1,...,Z_n, each with a variance of sigma^2, what would the variance of the mean, Z bar be?" Then we conclude the variance is sigma^2/n . 

My questions are: 

1.) when you say observations, do you mean random variables? If each Z_i was a single observation wouldn't it have variance 0? 

2.) Is what is essentially happening is that as we increase n and sample from more Z_i variables, on average, for large n, we will be more likely to pick values from many of the Z_i variables closer to the individual Z_i mean? Hence the variance will decrease as picking more values close to each of the individual Z_i mean values will keep the total mean closer to the true mean of Z bar? (where the true mean of Z bar is the average of the true mean of the Z_i variables)

3.) When you say "On average, each bagged tree makes use of about 2/3 of the observations."
What stipulations are required for the bagging process in order to ensure the 2/3 number? It seems if we had 100 training values and created 5 bagged training sets, where I set the number of data points to draw (with replacement) for each bagged training set to be a very high number, say 1000, then it would seem likely that each of the 5 bagged training sets would use close to 100% of the original 100 training examples. Alternatively I could set the number of data points to draw very small, and end up with the opposite answer, in both cases very far from 2/3. 

My question is, does that 2/3 number depend on how large you intend to make your bagged training sets in relation to how large your original training set? Is there some general rule people use for creating the size of each bagged training set? 

Thanks!

**Comment by LucyMcGowan** [comment]
1) Yes, I mean random variables, it's true the variance for a single observed value would be 0
2) Yes, you can see this mathematically:
*  the variance of the sum of independent random variables is the sum of their individual variances
*  if you have a bunch of independent variables Z1...Zn, each with a variance σ^2 the variance of the ∑Zi would be nσ^2
*  If you wanted the variance of the mean, it would be:
Var(∑Zi/n) = (1/n^2)Var(∑Zi) = (1/n^2)(nσ^2) = (σ^2)/n

3) The 2/3 rule is assuming that you are fully sampling with replacement (that is the number that you resample = the total sample size). In terms of a general rule for the size of each bagged training set, often it is _n_.  If you have n draws with replacement from n observations, the chance of not being selected is (1 - (1/n))^(n), which is approximately 1/3
