### ISSUE TITLE
Lab 06 Q2

### ISSUE THREAD

**Issue by juserrano** [sta-363-s20/community#79]
Hello Dr. @LucyMcGowan ,

I am still having issues figuring out what I should add to the ggplot code in question 2 (and subsequent plot questions) as I am not sure what we are trying to plot.
<img width="685" alt="2020-04-21" src="https://user-images.githubusercontent.com/59888434/79919804-11fd5100-83fd-11ea-8fa5-0c53def26445.png">
This is what I have so far for the rest of the code.

**Comment by LucyMcGowan** [comment]
You need to save the output from the second chunk of code there, that will have the rmse for each of the trees (that is what you’re plotting)

**Comment by juserrano** [comment]
Could you give me a tip? I am really lost on how to do that...

**Comment by juserrano** [comment]
Also, when I collect metrics for my random forest, my results are exactly the same as with bagging. Is this normal?
Here is the code for random forest

<img width="788" alt="2020-04-21 (1)" src="https://user-images.githubusercontent.com/59888434/79922724-41fb2300-8402-11ea-9988-fd9ffbbbc2c8.png">

**Comment by LucyMcGowan** [comment]
You need to specify mtry for bagging, the default is random Forest. Save the output like this:

```
rf_results <- rf_model %>%
  collect_metrics() %>%
  filter(.metric == “rmse”)
```

**Comment by juserrano** [comment]
Thank you! It works now!

**Comment by midupree** [comment]
@LucyMcGowan This is my coding, and this is the error I get for the plot.
<img width="722" alt="Screen Shot 2020-04-22 at 11 30 47 AM" src="https://user-images.githubusercontent.com/59888424/80001792-c98d7400-848c-11ea-8638-c090b0b8c3b5.png">
<img width="715" alt="Screen Shot 2020-04-22 at 11 31 25 AM" src="https://user-images.githubusercontent.com/59888424/80001817-d01beb80-848c-11ea-9e3f-16d703d848c8.png">

**Comment by walkerjohn97** [comment]
@midupree I'm having the same issue

**Comment by walkerjohn97** [comment]
@midupree I figured it out! change labs(y=mean) to labs(y="mean")

**Comment by midupree** [comment]
@walkerjohn97 still did not work:(

**Comment by LucyMcGowan** [comment]
@midupree you have to save the output, like I wrote in the comment above:

```
Bagged_results <- tuning_bag %>%
  collect_metrics() %>%
  filter(.metric == “rmse”)
```
