### ISSUE TITLE
HW 1 Exercise 1, Part 1.2

### ISSUE THREAD

**Issue by skywang0407** [sta-363-s20/community#8]
Hi Professor McGowan,
For 1.2 in Ex 1, what do you mean "test"?
Do you want us to compare the t-statistics of the two models or do you want us to code in the chunk?

Thanks!

**Comment by LucyMcGowan** [comment]
For exercise 1, there is not any R code needed. Test refers to a testing data set (as opposed to a training data set that would have been used to fit the original model)

**Comment by Cindyyyhey** [comment]
Hi Professor McGowan,
I'm still a little bit confused about the difference between training dataset and the testing dataset. why using the same model to fit them will lead to different results?

**Comment by LucyMcGowan** [comment]
You are **fitting** the model on the training data, you are **evaluating** it on the test data. So if you calculate a predicted y value using the test data, you would plug in the X values from the test data into the equation that you obtained using the training data.

**Comment by Cindyyyhey** [comment]
Got it! Thanks!

**Comment by TaylorFowlks** [comment]
I am confused of how we should think about the answer to question 1 @LucyMcGowan ? Would the training RSS for the cubic regression model be lower than the training RSS for the linear regression model since it has more predictors?

**Comment by LucyMcGowan** [comment]
This question is trying to get at the trade-off for bias and variance. So for the training data, think about which model (linear or cubic) would be more flexible, and how this would affect the RSS, then think about how this would or wouldn't be different if instead of calculating the RSS using training data, you used a new _testing_ data set.
