### ISSUE TITLE
Pruning decision tree

### ISSUE THREAD

**Issue by Cindyyyhey** [sta-363-s20/community#80]
Hi Professor McGowan,

I'm having trouble understanding this pruning equation. What is Yi? What does the Rm(box, predictor space) mean? Are we using this equation to find an ideal alpha? Or we use cross validation to get alpha first, then fit in to this equation. How much do we need to understand this equation for midterm 3?
Thanks in advance!
![屏幕快照 2020-04-21 下午8 21 04](https://user-images.githubusercontent.com/54655629/79928090-df108880-840f-11ea-8c4d-3cf1d35b40bc.png)

**Comment by LucyMcGowan** [comment]
* yi is the observed outcome
* Rm is the box that corresponds to the mth terminal node: here is a visual of the box from the slides: https://sta-363-s20.lucymcgowan.com/slides/16-decision-trees-reg.html#17
* you are using cross validation to get alpha

**Comment by Cindyyyhey** [comment]
Got it, thank you!
