### ISSUE TITLE
Unable to Knit

### ISSUE THREAD

**Issue by obranc97** [sta-363-s20/community#81]
Hi Professor McGowan,

When I try to knit the markdown file I am getting an error.
<img width="674" alt="Screen Shot 2020-04-22 at 10 47 13 AM" src="https://user-images.githubusercontent.com/59891943/79996850-ea52cb00-8486-11ea-81aa-b1cd68a773aa.png">

Do you know what this error means?

**Comment by LucyMcGowan** [comment]
it looks like you have two chunk labels that are the same (`metric filtered`) make sure the chunk labels are all unique

**Comment by obranc97** [comment]
Thank you!
