### ISSUE TITLE
Ranger or Rpart

### ISSUE THREAD

**Issue by walkerjohn97** [sta-363-s20/community#82]
Hey Dr. McGowan,

I'm a little confused on the difference between Rpart and Ranger when it comes to the set engine. For bagging, like in exercise 1, do we set engine to rpart or ranger? Thanks!

**Comment by LucyMcGowan** [comment]
You should set to `ranger`, `ranger` is for bagging and random forest, `rpart` is for decision trees (without any bootstrapping)
