### ISSUE TITLE
Tuning Error

### ISSUE THREAD

**Issue by walkerjohn97** [sta-363-s20/community#83]
Hey Dr. McGowan, 

When I run my code for Exercise 1, I also keep getting this tuning error. Can you help me? I don't understand what I'm doing wrong. 
<img width="512" alt="Screen Shot 2020-04-22 at 11 38 23 AM" src="https://user-images.githubusercontent.com/59891793/80002672-ebd3c180-848d-11ea-88ed-f9a67a9a4c4f.png">

**Comment by LucyMcGowan** [comment]
You didn't specify `tune()` for any of the parameters the `bagging_spec`

**Comment by walkerjohn97** [comment]
Figured it out! Thank you!
