### ISSUE TITLE
HW-01 EX-3 Dataset not found

### ISSUE THREAD

**Issue by LutionHan** [sta-363-s20/community#9]
Hi Dr. McGowan,

When I fit the model in HW-01, Ex-3, R tells me that

model <- lm(Sales ~ Price + Urban + US, data = Carseat);summary(model)
Error in is.data.frame(data) : object 'Carseat' not found

I have reloaded the package ISLR several times, and have tried Carseat and carseat, but none of them works.

Thanks.

**Comment by LucyMcGowan** [comment]
The dataset name is `Carseats` not `Carseat`

**Comment by LucyMcGowan** [comment]
I've updated the homework to reflect this (should be updated when you refresh) good catch, thank you! 

https://github.com/sta-363-s20/website/commit/8e2a7987d3e28a76655c4a72a92cae03e2650d26

**Comment by LutionHan** [comment]
Thanks!
